#ifndef PROOFSERVICE_LPR_PRINTER_GLOBAL_H
#define PROOFSERVICE_LPR_PRINTER_GLOBAL_H

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(proofServiceLprPrinterLog)

#endif // PROOFSERVICE_LPR_PRINTER_GLOBAL_H
