#ifndef PROOFSERVICE_LABEL_PRINTER_GLOBAL_H
#define PROOFSERVICE_LABEL_PRINTER_GLOBAL_H

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(proofServiceLabelPrinter)

#endif // PROOFSERVICE_LABEL_PRINTER_GLOBAL_H
